version: '3.8'

services:
  postgres:
    container_name: tool_hub_postgres
    image: postgres:14-alpine
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - tool_hub_network

  spring_backend:
    container_name: tool_hub_spring_backend
    build:
      context: ./tool-hub  
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ~/.m2:/root/.m2
    networks:
      - tool_hub_network

  next_frontend:
    container_name: tool_hub_next_frontend
    build:
      context: ./tool-hub-frontend  
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    depends_on:
      - spring_backend
    ports:
      - "3000:3000"
    networks:
      - tool_hub_network

volumes:
  postgres_data: {}

networks:
  tool_hub_network:
    driver: bridge